"use client";
import { useState } from "react";
import { ArrowUpRight, Github, Linkedin, Mail, Menu, MoveUpRight, X } from "lucide-react";

const projects=[
{no:"01",title:"Hyundai Sunset Road",type:"Automotive / Digital Experience",desc:"A refined retail experience for discovering cars, promotions, test drives, and showroom services.",tags:["Next.js","Supabase","UX/UI"],visual:"visual-one"},
{no:"02",title:"PlayMart",type:"Commerce / Product Design",desc:"A high-conversion digital marketplace concept with product discovery, checkout, payment states, and account flows.",tags:["React","Tailwind","Railway"],visual:"visual-two"},
{no:"03",title:"Private Lab",type:"Interface / Experiments",desc:"A collection of interaction experiments exploring motion, visual systems, dashboards, and tiny useful tools.",tags:["React","Motion","Prototyping"],visual:"visual-three"}
];
const capabilities=[
["01","Product Direction","From rough idea to a clear product structure, user journey, and visual language."],
["02","UI / UX Design","Interfaces that feel intentional — typography, spacing, hierarchy, motion, and responsive behavior."],
["03","Full-Stack Build","Modern React applications with APIs, data, auth, deployment, and production-minded architecture."],
["04","Polish & Motion","The last 10%: transitions, micro-interactions, visual rhythm, loading states, and details that make products feel expensive."]
];
function navTo(id){document.getElementById(id)?.scrollIntoView({behavior:"smooth",block:"start"})}

export default function Home(){
 const [open,setOpen]=useState(false);const [copied,setCopied]=useState(false);
 const copyEmail=async()=>{try{await navigator.clipboard.writeText("hello@kimrayy.dev");setCopied(true);setTimeout(()=>setCopied(false),1600)}catch{}};
 const nav=id=>{setOpen(false);navTo(id)};
 return <main className="site-shell grain">
  <header className="fixed top-0 left-0 right-0 z-40 pt-3 sm:pt-4"><div className="container-premium"><div className="nav-glass rounded-full px-4 py-2.5 sm:px-5"><div className="flex items-center justify-between">
   <button onClick={()=>nav("home")} className="flex items-center gap-2.5" aria-label="Home"><span className="grid h-8 w-8 place-items-center rounded-full bg-[#10100f] text-[11px] font-black text-white">K</span><span className="hidden text-xs font-black tracking-[.18em] sm:inline">KIMRAYY®</span></button>
   <nav className="hidden items-center gap-7 md:flex">{["Work","About","Capabilities","Contact"].map(i=><button key={i} onClick={()=>nav(i.toLowerCase())} className="text-xs font-semibold text-black/55 transition hover:text-black">{i}</button>)}</nav>
   <div className="flex items-center gap-2"><button onClick={copyEmail} className="hidden rounded-full bg-[#10100f] px-4 py-2 text-[11px] font-bold text-white transition hover:-translate-y-0.5 sm:inline-flex">{copied?"Copied":"Let's talk"}</button><button onClick={()=>setOpen(true)} className="grid h-9 w-9 place-items-center rounded-full border border-black/10 bg-white/65 md:hidden" aria-label="Open menu"><Menu size={16}/></button></div>
  </div></div></div></header>
  {open&&<div className="fixed inset-0 z-50 bg-[#f4f1ea] p-4 md:hidden"><div className="container-premium flex h-full max-w-2xl flex-col"><div className="flex items-center justify-between py-3"><span className="text-xs font-black tracking-[.18em]">KIMRAYY®</span><button onClick={()=>setOpen(false)} className="grid h-10 w-10 place-items-center rounded-full border border-black/10"><X size={18}/></button></div><div className="flex flex-1 flex-col justify-center gap-5">{["Work","About","Capabilities","Contact"].map((item,i)=><button key={item} onClick={()=>nav(item.toLowerCase())} className="text-left font-display text-5xl leading-none">{String(i+1).padStart(2,"0")} <span className="text-black/25">/</span> {item}</button>)}</div><div className="border-t border-black/10 py-5 text-xs text-black/50">Available for select freelance & product collaborations.</div></div></div>}
  <section id="home" className="relative min-h-screen overflow-hidden pt-28 sm:pt-32"><div className="hero-grid absolute inset-0"/><div className="container-premium relative flex min-h-[calc(100vh-110px)] items-center"><div className="grid w-full items-center gap-14 lg:grid-cols-[1.08fr_.92fr]">
   <div className="reveal"><p className="section-kicker">Independent designer & developer</p><h1 className="font-display mt-5 text-[clamp(4rem,10vw,8.7rem)] leading-[.84]"><span className="block">Digital</span><span className="block italic">work,</span><span className="shimmer block">beautifully built.</span></h1><p className="reveal reveal-delay-1 mt-7 max-w-xl text-base leading-8 text-black/55 sm:text-lg">I turn ideas into sharp, modern digital products — balancing strategy, interface craft, code, and the little details people feel before they notice.</p><div className="reveal reveal-delay-2 mt-8 flex flex-wrap items-center gap-3"><button onClick={()=>nav("work")} className="inline-flex items-center gap-2 rounded-full bg-[#10100f] px-5 py-3 text-xs font-bold text-white transition hover:-translate-y-0.5">Explore selected work <ArrowUpRight size={15}/></button><button onClick={()=>nav("about")} className="inline-flex items-center gap-2 rounded-full border border-black/10 bg-white/45 px-5 py-3 text-xs font-bold transition hover:bg-white">About me <MoveUpRight size={14}/></button></div><div className="mt-10 flex flex-wrap gap-x-8 gap-y-3 text-[10px] font-bold uppercase tracking-[.18em] text-black/40"><span>Based in Bali</span><span>Working worldwide</span><span>Available 2026</span></div></div>
   <div className="reveal reveal-delay-2 flex justify-center lg:justify-end"><div className="orbit float" aria-hidden="true"><div className="orbit-core"/><span className="orbit-dot dot-a"/><span className="orbit-dot dot-b"/><span className="orbit-dot dot-c"/><div className="absolute inset-0 grid place-items-center text-center"><div><div className="text-[10px] font-bold uppercase tracking-[.24em] text-black/45">Selected discipline</div><div className="font-display mt-2 text-4xl">Design × Code</div><div className="mt-2 text-xs text-black/45">products / web / systems</div></div></div><div className="absolute left-[8%] top-[20%] rounded-full bg-white/70 px-3 py-2 text-[10px] font-bold uppercase tracking-[.12em] shadow-lg shadow-black/5">UI/UX</div><div className="absolute right-0 bottom-[25%] rounded-full bg-[#10100f] px-3 py-2 text-[10px] font-bold uppercase tracking-[.12em] text-white shadow-lg">React</div><div className="absolute bottom-[9%] left-[31%] rounded-full bg-[#d8be8e]/75 px-3 py-2 text-[10px] font-bold uppercase tracking-[.12em]">Systems</div></div></div>
  </div></div><div className="absolute bottom-6 left-1/2 -translate-x-1/2 text-[10px] font-bold uppercase tracking-[.2em] text-black/35">Scroll to explore ↓</div></section>
  <section id="work" className="bg-[#ebe7de] py-24 sm:py-32"><div className="container-premium"><div className="flex flex-col gap-7 border-b border-black/10 pb-8 md:flex-row md:items-end md:justify-between"><div><p className="section-kicker">Selected work</p><h2 className="font-display mt-3 text-5xl leading-none sm:text-7xl">Built with intent.</h2></div><p className="max-w-sm text-sm leading-7 text-black/50">A few projects that show how I think across product strategy, visual design, engineering, and interaction.</p></div>
   <div className="mt-10 space-y-7">{projects.map(p=><article key={p.no} className="project-card p-3 sm:p-4"><div className={`project-visual ${p.visual}`}><div className="absolute left-5 top-5 flex items-center gap-2 rounded-full border border-white/20 bg-black/10 px-3 py-2 text-[10px] font-bold uppercase tracking-[.16em] text-white backdrop-blur">Project {p.no}</div><div className="visual-ui"><div className="bar"/><div className="w-2/3 text-2xl font-black tracking-tight text-white sm:text-4xl">{p.title}</div><div className="row mt-6"/><div className="row"/></div><div className="absolute bottom-5 right-5 grid h-12 w-12 place-items-center rounded-full bg-white/85 text-black shadow-xl"><ArrowUpRight size={18}/></div></div><div className="grid gap-6 p-4 sm:p-6 lg:grid-cols-[1fr_1.3fr_auto] lg:items-end"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-black/35">{p.type}</p><h3 className="font-display mt-2 text-3xl sm:text-4xl">{p.title}</h3></div><p className="max-w-xl text-sm leading-7 text-black/55">{p.desc}</p><div className="flex flex-wrap justify-start gap-2 lg:justify-end">{p.tags.map(t=><span key={t} className="rounded-full border border-black/10 bg-white/60 px-3 py-1.5 text-[10px] font-bold">{t}</span>)}</div></div></article>)}</div>
  </div></section>
  <section id="about" className="py-24 sm:py-32"><div className="container-premium"><div className="grid gap-14 lg:grid-cols-[.78fr_1.22fr] lg:gap-24"><div><p className="section-kicker">About</p><h2 className="font-display mt-3 text-5xl leading-[.95] sm:text-7xl">Quietly obsessed with quality.</h2></div><div><p className="text-xl leading-9 text-black/72 sm:text-2xl">I like digital products that feel calm, clear, and considered. My sweet spot sits between product thinking and hands-on implementation — designing the interface, writing the components, and polishing the experience until every piece belongs.</p><div className="mt-10 grid gap-5 sm:grid-cols-3"><div className="metric-card"><p className="text-3xl font-black">04+</p><p className="mt-2 text-xs leading-5 text-black/45">Years exploring web & product work</p></div><div className="metric-card"><p className="text-3xl font-black">∞</p><p className="mt-2 text-xs leading-5 text-black/45">Curiosity for new tools and ideas</p></div><div className="metric-card"><p className="text-3xl font-black">1×</p><p className="mt-2 text-xs leading-5 text-black/45">Standard: details should feel intentional</p></div></div><div className="mt-10 flex flex-wrap gap-3"><a href="https://github.com/Kimrayy" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-full border border-black/10 px-4 py-2.5 text-xs font-bold hover:bg-black hover:text-white"><Github size={15}/> GitHub</a><a href="https://www.linkedin.com/" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-full border border-black/10 px-4 py-2.5 text-xs font-bold hover:bg-black hover:text-white"><Linkedin size={15}/> LinkedIn</a><a href="mailto:hello@kimrayy.dev" className="inline-flex items-center gap-2 rounded-full border border-black/10 px-4 py-2.5 text-xs font-bold hover:bg-black hover:text-white"><Mail size={15}/> Email</a></div></div></div></div></section>
  <section id="capabilities" className="dark-section py-24 sm:py-32"><div className="container-premium"><div className="flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div><p className="section-kicker !text-[#d7bb87]">Capabilities</p><h2 className="font-display mt-3 max-w-3xl text-5xl leading-[.95] sm:text-7xl">The craft behind the screen.</h2></div><p className="max-w-sm text-sm leading-7 text-white/45">Strategy, design, engineering, and polish working as one system.</p></div><div className="mt-12 grid gap-px overflow-hidden rounded-[28px] border border-white/8 bg-white/6">{capabilities.map(([no,title,desc])=><div key={no} className="dark-card group grid gap-7 p-7 transition hover:bg-[#1b1b18] sm:grid-cols-[80px_1fr_1.15fr] sm:p-9"><span className="text-[10px] font-bold tracking-[.18em] text-white/25">{no}</span><div className="flex items-start gap-3"><span className="mt-1 h-2 w-2 shrink-0 rounded-full bg-[#d7bb87]"/><h3 className="font-display text-3xl sm:text-4xl">{title}</h3></div><p className="max-w-lg text-sm leading-7 text-white/45">{desc}</p></div>)}</div><div className="mt-16 overflow-hidden border-y border-white/10 py-5"><div className="marquee">{["NEXT.JS","REACT","TAILWIND","BOOTSTRAP","SUPABASE","RAILWAY","UI/UX","PRODUCT","MOTION","SYSTEMS","NEXT.JS","REACT","TAILWIND","BOOTSTRAP"].map((item,i)=><div key={i} className="flex items-center gap-5 text-[11px] font-bold tracking-[.24em] text-white/32"><span>{item}</span><span className="h-1 w-1 rounded-full bg-[#d7bb87]"/></div>)}</div></div></div></section>
  <section id="contact" className="dark-section pb-20 sm:pb-28"><div className="container-premium"><div className="contact-ring rounded-[34px] bg-[#11110f] p-8 sm:p-12 lg:p-16"><div className="grid items-end gap-10 lg:grid-cols-[1fr_auto]"><div><p className="section-kicker !text-[#d7bb87]">Contact</p><h2 className="font-display mt-4 max-w-4xl text-[clamp(3.4rem,8vw,7.3rem)] leading-[.84]">Have a good idea? <span className="italic text-white/45">Let’s make it real.</span></h2></div><div className="lg:pb-1"><button onClick={copyEmail} className="group inline-flex items-center gap-3 rounded-full bg-[#f4f1ea] px-5 py-3 text-xs font-black text-[#10100f] transition hover:-translate-y-0.5"><Mail size={15}/> {copied?"Email copied":"hello@kimrayy.dev"} <ArrowUpRight size={15} className="transition group-hover:translate-x-0.5 group-hover:-translate-y-0.5"/></button></div></div></div><footer className="flex flex-col gap-4 border-t border-white/10 pt-8 text-[10px] font-bold uppercase tracking-[.16em] text-white/30 sm:flex-row sm:items-center sm:justify-between"><span>© 2026 Kimrayy. Built with care.</span><div className="flex gap-5"><a href="https://github.com/Kimrayy" target="_blank" rel="noreferrer" className="hover:text-white">GitHub</a><a href="https://www.linkedin.com/" target="_blank" rel="noreferrer" className="hover:text-white">LinkedIn</a><a href="mailto:hello@kimrayy.dev" className="hover:text-white">Mail</a></div></footer></div></section>
 </main>
}
